# This Dockerfile is not intended to be directly built. Instead, it is embedded
# within the Build Controller binary (see //go:embed) and templatized with
# certain options around base image pullspecs.
#
# Decode and extract the MachineConfig from the gzipped ConfigMap and move it
# into position. We do this in a separate stage so that we don't have the
# gzipped MachineConfig laying around.
FROM registry.ci.openshift.org/ocp/4.18-2024-11-21-144815@sha256:be6f713e7f9ed10689cfde90bb93fd65cad98a7da6e351b739b637336cdd9fb3 AS extract
COPY ./machineconfig/machineconfig.json.gz /tmp/machineconfig.json.gz
RUN mkdir -p /etc/machine-config-daemon && \
	cat /tmp/machineconfig.json.gz | base64 -d | gunzip - > /etc/machine-config-daemon/currentconfig

FROM registry.ci.openshift.org/ocp/4.18-2024-11-21-144815@sha256:be6f713e7f9ed10689cfde90bb93fd65cad98a7da6e351b739b637336cdd9fb3 AS configs
# Copy the extracted MachineConfig into the expected place in the image.
COPY --from=extract /etc/machine-config-daemon/currentconfig /etc/machine-config-daemon/currentconfig
# Do the ignition live-apply, extracting the Ignition config from the MachineConfig.
# Not sure why Ignition explicitly requires the container env var to be set
# since it should be set by the container runtime / builder.
RUN container="oci" exec -a ignition-apply /usr/lib/dracut/modules.d/30ignition/ignition --ignore-unsupported <(cat /etc/machine-config-daemon/currentconfig | jq '.spec.config') && \
	ostree container commit
# Install any extensions specified

# Mount the extensions image to use the content from it
# and add the extensions repo to /etc/yum.repos.d/coreos-extensions.repo
RUN --mount=type=bind,from=registry.ci.openshift.org/ocp/4.18-2024-11-21-144815@sha256:8fd89dbf2b3edc051c6f1b69b36b394a8232ff5517e6d093c321939fa97c4a78,source=/,target=/tmp/mco-extensions/os-extensions-content,bind-propagation=rshared,rw,z \
    echo -e "[coreos-extensions]\n\
enabled=1\n\
metadata_expire=1m\n\
baseurl=/tmp/mco-extensions/os-extensions-content/usr/share/rpm-ostree/extensions/\n\
gpgcheck=0\n\
skip_if_unavailable=False" > /etc/yum.repos.d/coreos-extensions.repo && \
    chmod 644 /etc/yum.repos.d/coreos-extensions.repo && \
    extensions="usbguard" && \
    echo "Installing extension packages: $extensions" && \
    rpm-ostree install $extensions && \
    rm /etc/yum.repos.d/coreos-extensions.repo
RUN ostree container commit


COPY ./openshift-config-user-ca-bundle.crt /etc/pki/ca-trust/source/anchors/openshift-config-user-ca-bundle.crt
RUN update-ca-trust

LABEL machineconfig=rendered-layered-675e73aee04345b2750696af3dc8fe52
LABEL machineconfigpool=layered
LABEL releaseversion=4.18.0-0.ci-2024-11-21-144815
LABEL baseOSContainerImage=registry.ci.openshift.org/ocp/4.18-2024-11-21-144815@sha256:be6f713e7f9ed10689cfde90bb93fd65cad98a7da6e351b739b637336cdd9fb3


FROM configs AS final
RUN rpm-ostree install tree && \
  ostree container commit



